services:
  - type: web
    name: sandsu-student-online
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: DATA_DIR
        value: /var/data
    disk:
      name: sandsu-data
      mountPath: /var/data
      sizeGB: 1
