services:
  - type: web
    name: sandsu-online
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SANDSU_DATA_DIR
        value: /var/data
      - key: SANDSU_PASSWORD
        sync: false
      - key: SANDSU_SECRET
        sync: false
    disk:
      name: sandsu-data
      mountPath: /var/data
      sizeGB: 1
